# Generated by Django 3.2.8 on 2021-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hdd',
            field=models.CharField(choices=[('512 Gb', '512 Gb'), ('1 Tb', '1 Tb'), ('5 Tb', '5 Tb'), ('10 Tb', '10 Tb')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='memory',
            field=models.CharField(choices=[('8 Gb', '8 Gb'), ('16 Gb', '16 Gb'), ('32 Gb', '32 Gb'), ('64 Gb', '64 Gb')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vcpu',
            field=models.CharField(choices=[('8 core', '8 core'), ('16 core', '16 core'), ('32 core', '32 core'), ('64 core', '64 core')], max_length=200, null=True),
        ),
    ]
