# Generated by Django 3.2.8 on 2021-10-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20211021_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
